global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'trackgeek-api'
    static_configs:
      - targets: ['192.168.0.128:40287']
    metrics_path: '/prometheus'

  - job_name: 'trackgeek-postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'trackgeek-redis'
    static_configs:
      - targets: ['redis-exporter:9121']