name: Check Style Code

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
      - develop

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun ci

      - name: Check formatting
        run: bun format
        
      - name: Check linting
        run: bun lint
